include(":util")
include(":backend-common")
include(":json")
include(":client-common")
include(":client")
include(":client-android")
include("server-common")
include("server-pi")
include("server-pc-stub")

includeBuild("includeBuild")
